### ISSUE TITLE
howto

### ISSUE THREAD

**Issue by vtolstov** [sbyx/ohybridproxy#1]
Can you provide some howtos what i need to run to get things working?
For example what part of mDNSResponder i need to keep run, what cmdline for ohybridproxy in this case...
I want to forward mdns request from dnsmasq to this proxy.

**Comment by fingon** [comment]
dnsmasq doesn't really do mdns. This code isn't very usable standalone, I recommend http://www.homewrt.org/doku.php if you need home router that does it, or have it + dnsmasq autoconfigured using https://github.com/sbyx/hnetd (it works on any Linux, but probably needs 'some work' outside OpenWrt).

**Comment by vtolstov** [comment]
@fingon I know that. I'm patch dnsmasq to able forward mdns request to external dns server
