### ISSUE TITLE
DNS rebind protection should be disabled for .home by default

### ISSUE THREAD

**Issue by toreanderson** [sbyx/ohybridproxy#3]
I've noticed that if I query Homenet my router _y_ for an **IN A** record belonging to a host attached router _x_, no answer is forthcoming. However, if I ask _x_ directly, I do get an answer:

```
$ dig +short @y.home. lust.e1.x.home. IN A
$ dig +short @x.home. lust.e1.x.home. IN A
10.0.0.115
```

Running `tcpdump` on the transit link between _x_ and _y_ reveals that _y_ **does** forward the request to _x_ and that it **does** receive an answer:

```
08:48:17.832315 IP6 2a02:fe0:c410:d9d::54.19148 > 2a02:fe0:c410:d95::38.domain: 41578+ [1au] A? lust.e1.x.home. (43)
08:48:17.832753 IP6 2a02:fe0:c410:d95::38.domain > 2a02:fe0:c410:d9d::54.19148: 41578* 1/0/1 A 10.0.0.115 (59)
```

However `logread` on _y_ reveals what's going wrong here:

```
Tue Oct 13 08:48:17 2015 daemon.warn dnsmasq[3551]: possible DNS-rebind attack detected: lust.e1.x.home
```

Adding `list rebind_domain 'home'` to the `config dnsmasq` section in `/etc/config/dhcp` on _y_ successfully works around this problem. In my opinion, this should be made the default (at least if Homenet software is installed).

**Comment by fingon** [comment]
Already fixed in c0b0c31b8fa4fbe47208e49685ccc9976532738a.
